# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f637932b0c3c883c2d15670a4497eb9e0a7fb48355862a5027a3a496dd29f4e187603d0ad7953491532ee9dde59276347b045e53051486b212dea0a8f76caf4e

test:
  secret_key_base: 4c4a8c06dee8e4dde0225557d80e511d93b1892a76560c98fbb402ec2aaa28984efbfd365ea305beb313af01c6c3a353e3a01d63030d5f67a2a6da2757384a36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
